spring:
  application:
    name: kotlin-spring-rest

springdoc:
  swagger-ui:
    path: /
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    filter: true

  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /v3/api-docs


server:
  port: 8080