spring:
  application:
    name: kotlin-spring-rest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/people_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    filter: true

  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /v3/api-docs


server:
  port: 8080